# Generated by Django 2.0 on 2018-12-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='popularity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
